os: osx
language: go

go:
  - 1.6

before_install:
  - go get github.com/stretchr/testify
  - go get github.com/BurntSushi/toml
  - go get github.com/progrium/go-basher

script:
  - ./test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
