language: go

go:
	- 1.6

before_install:
	- go get github.com/stretchr/testify

script:
	- go test -coverprofile=coverage.txt -covermode=atomic

after_success:
	- bash <(curl -s https://codecov.io/bash)
